fix: Add internal/external credhub url
cloudfoundry-incubator/kubecf pull request #1398
Opened 2020-09-29 11:57 UTC by mudler

Credhub otherwise advertizes to the client the internal url that can't be resolved:

```
Setting the target url: https://credhub.172.18.0.2.xip.io
Warning: The targeted TLS certificate has not been verified for this connection.
Warning: The --skip-tls-validation flag is deprecated. Please use --ca-cert instead.
UAA error: Post https://uaa.service.cf.internal:8443/oauth/token: dial tcp: lookup uaa.service.cf.internal on 10.96.0.10:53: no such host
```

## Description
This changes sets the internal and external url of uaa in credhub correctly, so that the config yaml in the credhub pod results in the following:

```yaml
/:/var/vcap/jobs/credhub# cat config/application/auth-server.yml 
---
auth-server:
  url: https://uaa.172.18.0.2.xip.io
  trust_store: "/var/vcap/jobs/credhub/config/trust_store.jks"
  trust_store_password: "${TRUST_STORE_PASSWORD}"
  internal_url: https://uaa.kubecf.svc:8443
```

## Motivation and Context
Otherwise the pod running the tests for #840 fails for the following error 

## How Has This Been Tested?
Locally

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-09-29 12:00 UTC, viovanov approved these changes

2020-09-29 18:02 UTC, viovanov commented
@mudler this seems to break cats for credhub

2020-09-29 18:03 UTC, viovanov requested changes
fails cats

2020-09-30 08:23 UTC, mudler commented
@viovanov :cat: fixed!

2020-09-30 11:37 UTC, viovanov commented
thx @mudler :D

2020-09-30 11:37 UTC, viovanov approved these changes

2020-09-30 11:40 UTC, merged