feat: RFD 0008 Public Roadmap
cloudfoundry-incubator/kubecf pull request #1433
Opened 2020-10-03 12:27 UTC by fargozhu

## Description

The goal is to give the community a place where they can find the project features, their state and a potential timeline.

## Motivation and Context

Since KubeCF is the core of some of the downstream products, I do believe it's important to give a glimpse of what the team collective decided what is important to have and/or explore, based on community feedback and suggestions.

Note: it's not a place for public discussion (since that should have happen before we reach this point)!

2020-10-20 14:14 UTC, viccuad commented on doc/rfd/rfd/0008/README.md
> +Any feature can be abandoned by team decision, independently of it state and the reason well
```suggestion
Any feature can be abandoned by team decision independently of its state, provided there's a reason well
```

2020-10-20 14:14 UTC, viccuad submitted a review, later dismissed

2020-10-26 19:04 UTC, andreas-kupries requested changes
Lots of general re-phrasing for clarity.

2020-10-26 19:04 UTC, andreas-kupries commented on doc/rfd/rfd/0008/README.md
> +feature on a particular date. The main goal is to give the community the team high level development
```suggestion
feature on a particular date. The main goal is to show the community the team's high level development
```

2020-10-26 19:04 UTC, andreas-kupries commented on doc/rfd/rfd/0008/README.md
> +plan, so please do not rely on this roadmap to make any internal decision.
```suggestion
plan. Please __do not__ rely on this roadmap to make any internal decision.
```

2020-10-26 19:04 UTC, andreas-kupries commented on doc/rfd/rfd/0008/README.md
> +particular feature.
Rephrased:
```
The roadmap is arranged in columns, each representing a quarter year.
The contents indicate our intent on when to release any particular feature.
Note that an intent is not a promise.
```

2020-10-27 10:29 UTC, fargozhu commented on doc/rfd/rfd/0008/README.md
> +lead to potential delays, since their main purpose is to gather community feedback.
Even for me ;)

I am rephrasing it....

2020-10-27 18:45 UTC, andreas-kupries requested changes
Nits left.

2020-10-27 18:45 UTC, andreas-kupries commented on doc/rfd/rfd/0008/README.md
> +which phase they are and when they may come available.
```suggestion
which phase they are in and when they may come available.
```

2020-10-27 18:45 UTC, andreas-kupries commented on doc/rfd/rfd/0008/README.md
> +intent to release a feature.
```
- ... it indicates when are we intent to release a feature.
+ .. it indicates when we intend to release a feature.
```
`intent` is the thing/noun, `(to) intend` the action/verb.

2020-10-28 15:12 UTC, viovanov commented
👍

2020-11-02 12:28 UTC, merged