fix: brain tests for eirini
cloudfoundry-incubator/kubecf pull request #1445
Opened 2020-10-05 23:57 UTC by andreas-kupries

## Description

- disable tcp routing tests, not supported
- bring in fix for metron test (brain test release 0.0.15)

## Motivation and Context

See #1371 

## How Has This Been Tested?

Local minikube deployment with eirini and diego. Latest master head, operator `6.1.10+0.g7b1a5f2f`.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-07 22:29 UTC, jandubois approved these changes
I wonder why we don't disable routing-api under Eirini instead? If it doesn't work, why let the user enable it?

@f0rmiga says:

> If the gorouter misses an update from nats, it can sync with the routing-api to keep the correct state.

But I don't understand how that would work if Eirini never emits any routes to routing-api in the first place.

2020-10-08 00:40 UTC, f0rmiga commented
> I wonder why we don't disable routing-api under Eirini instead? If it doesn't work, why let the user enable it?
> 
> @f0rmiga says:
> 
> > If the gorouter misses an update from nats, it can sync with the routing-api to keep the correct state.
> 
> But I don't understand how that would work if Eirini never emits any routes to routing-api in the first place.

It does emit routes. It just doesn't emit the TCP ones.

2020-10-08 00:45 UTC, f0rmiga commented on chart/assets/operations/instance_groups/brain-tests.yaml
> +{{- end }}
I _think_ this does what you want.

```suggestion
          tcprouting:
            enabled: {{ and .Values.features.routing_api.enabled (not .Values.features.eirini.enabled) }}
          insecure_registry:
            enabled: {{ and .Values.features.routing_api.enabled (not .Values.features.eirini.enabled) }}
```

2020-10-08 00:47 UTC, f0rmiga requested changes

2020-10-08 00:47 UTC, f0rmiga commented on chart/assets/operations/instance_groups/brain-tests.yaml
> +{{/* DROP when eirini has proper tcp routing support
```suggestion
{{/* Enable these tests when Eirini has proper TCP routing support.
```

2020-10-08 01:08 UTC, jandubois commented
@f0rmiga says
> > > If the gorouter misses an update from nats, it can sync with the routing-api to keep the correct state.
> > 
> > But I don't understand how that would work if Eirini never emits any routes to routing-api in the first place.
> 
> It does emit routes. It just doesn't emit the TCP ones.

Still confused: Eirini emits routes to gorouter. Does it also emit routes to the routing-api? Or how does it learn about the routes? Is there some document that explains how this works?

2020-10-08 01:21 UTC, f0rmiga commented
@jandubois Hmmm indeed it doesn't publish to the routing-api, only to nats (which is what the gorouter uses). You can check what I'm saying here:
https://github.com/cloudfoundry-incubator/eirini/blob/3bc2929aa05d437520da7df2e214edd1af0c941a/route/emitter.go#L106
https://github.com/cloudfoundry-incubator/eirini/blob/3bc2929aa05d437520da7df2e214edd1af0c941a/route/emitter.go#L28
https://github.com/cloudfoundry-incubator/eirini/blob/3bc2929aa05d437520da7df2e214edd1af0c941a/route/emitter.go#L51

I reviewed https://docs.cloudfoundry.org/concepts/cf-routing-architecture.html and if the gorouter misses a message from nats, it will need to wait for another emit event from the route emitter.

2020-10-08 01:26 UTC, jandubois commented
> indeed it doesn't publish to the routing-api, only to nats

So doesn't it make more sense to disable `routing-api` until Eirini supports it?

In which case this PR should be replaced with an entry in `chart/config/unsupported.yaml` that displays an error when the user wants to enable routing-api with Eirini.

Next question: why do we even make routing-api configurable? why would someone want to disable it when running with Diego?

2020-10-08 01:29 UTC, f0rmiga commented
@jandubois Yes, it does make sense to disable routing-api - I agree with that. Having the option to disable it was a request from IBM (I think the PR to being able to disable it came from @qu1queee a while ago).

2020-10-08 01:30 UTC, f0rmiga commented
@andreas-kupries I'll reject this PR in favour of disabling routing-api when Eirini is enabled.

2020-10-08 01:30 UTC, closed without merging

2020-10-08 02:03 UTC, jandubois commented
> Having the option to disable it was a request from IBM (I think the PR to being able to disable it came from @qu1queee a while ago).

Indeed, it was #544 

The problem I'm struggling with is that I would like the default to be `enabled` under Diego, but `disabled` under Eirini, but we have no good mechanism to do that (that isn't confusing to the user).

Otherwise you have to specify a lot of additional settings to enable Eirini:

```
helm install ... --set install_stacks={sle15} --set features.eirini.enabled=true --set features.routing_api.enabled=false
```

The best I can currently think of is leaving the flag as `nil` and adding a comment:

```
features:
  routing_api:
    # default is true for Diego, but false for Eirini
    enabled: ~
```

and then set the appropriate default in `chart/templates/_features.yaml`:

```
{{- if kindIs "invalid" $.Values.features.routing_api.enabled }}
  {{- $_ := set $.Values.features.routing_api "enabled" (not $.Values.features.eirini.enabled) }}
{{- end }}
```

Of course needs a corresponding change in the schema to allow the null value too.

Not really fond of it either, but nothing else comes to mind right now (well, except forcing the user to disable it under Eirini).

2020-10-08 02:33 UTC, jandubois commented
> # default is true for Diego, but false for Eirini

Actually, the comment should explain that there is no point in enabling it under Eirini, so something like

```
# enabled by default, except under Eirini, where the routing-api is not (yet) supported
```

2020-10-08 17:01 UTC, andreas-kupries commented
I believe I understand the discussion now. Will make a new PR based on @jandubois idea. As hackish as it looks it may be the only way of doing it.