refactor!: make database a singleton
cloudfoundry-incubator/kubecf pull request #1462
Opened 2020-10-07 21:15 UTC by f0rmiga

## Description

Removed the possibility of doing HA with the PXC database provided as part of KubeCF. It's currently not feasible to maintain a reliable HA setup as part of KubeCF.

## Motivation and Context

When the active node doing writes is terminated in the middle of replication (e.g. going from SA to HA as part of an upgrade), the data is left broken.

## How Has This Been Tested?

Locally. CI.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2020-10-07 21:21 UTC, mook-as requested changes
Please edit `unsupported.yaml` to explicitly let users know that this is no longer supported.

/cc @fargozhu for release notes.

2020-10-07 21:21 UTC, mook-as commented on chart/templates/database/db-statefulset.yaml
> +      # done right and to maintain as part of KubeCF. For an HA database, prefer
```suggestion
      # right and to maintain as part of KubeCF. For an HA database, prefer
```

2020-10-07 21:21 UTC, mook-as commented on chart/values.yaml
> -    instances: ~
Huh, the schema around sizing is a mess. Not for this PR, though.

2020-10-07 21:26 UTC, f0rmiga commented on chart/templates/database/db-statefulset.yaml
> +          {{- list . "database" | include "component.selector" | nindent 10 }}
Ahhh I picked from your commit... I hope this is no problem. We can merge your PR first. This PR won't get a merge conflict, I think.

2020-10-07 21:34 UTC, f0rmiga commented
@mook-as Please, check https://github.com/cloudfoundry-incubator/kubecf/pull/1462/commits/b31d2156910b2cfc25c85b80422c845e245adc79 if it's the expected message.

2020-10-07 22:25 UTC, mook-as requested changes
Nitpicks around phrasing.

2020-10-07 22:25 UTC, mook-as commented on chart/config/unsupported.yaml
> +    using a specialized external one.
Hmm, for user-facing text we should probably avoid using abbreviations.
```suggestion
  # Do not allow replicas for the database; doing this well in Kubernetes is
  # more effort than we can expend, and is better handled by external databases.
  sizing.database.instances: >
    Database replicas are not supported.
    KubeCF does not support highly available database configurations;
    please use an external database instead.
```

We don't _really_ need to say why in the error message (but putting it in a comment near the message is probably useful).  Details about Galera etc. would definitely belong more in a comment, I think.

Hmm, should probably mention [the documentation](https://kubecf.io/docs/deployment/kubernetes-deploy/#external-database).

2020-10-07 22:25 UTC, mook-as commented on chart/templates/database/db-statefulset.yaml
> +          {{- list . "database" | include "component.selector" | nindent 10 }}
No worries; as long as the code lands it's fine. It just seemed like it was unrelated :)

2020-10-07 22:54 UTC, jandubois commented
Is it safe to downgrade the database from HA to SA when upgrading kubecf? If not, then maybe the "unsupported" error should include some guidance to scale down the database *before* upgrading? (Assuming that is safe; or can that too still lead to data loss?)

2020-10-08 01:06 UTC, f0rmiga commented
> Is it safe to downgrade the database from HA to SA when upgrading kubecf? If not, then maybe the "unsupported" error should include some guidance to scale down the database _before_ upgrading? (Assuming that is safe; or can that too still lead to data loss?)

@jandubois Going from HA to SA should be safe if the active replica is the `database-0`.
@viovanov Is there a way to instruct the active-passive controller to use the `database-0`?

2020-10-08 08:52 UTC, viovanov commented
@f0rmiga afaik it will always scale to the 0 ordinal

2020-10-08 08:52 UTC, viovanov approved these changes

2020-10-08 08:53 UTC, merged