feat: CI: GHA: brains, internetless, and CCDB rotation
cloudfoundry-incubator/kubecf pull request #1610
Opened 2020-11-20 02:10 UTC by mook-as

## Description
This adds some of the missing parts of the existing concourse-based pipeline to GitHub Actions:
- Runs the brains tests
- Runs the CCDB rotation tests
- Runs the internetless tests (#1148)

## Motivation and Context
This should be the last part of #1144

## How Has This Been Tested?
Deployed & ran on my fork on KubeCF.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code has security implications.
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Additional information:
- The network policy stuff for internetless tests is from catapult.
- So is the technique for patching the runtime properties for the CATS QuarksJob to run just the internetless suite.
  - I changed it a bit so the property patching is separate from what properties to patch; we could perhaps later change the Eirini config generation to use normal + a step to patch the test suites (so that it is more visible).
- I'm splitting out the experimental flags to separate flags, so that it is easier to adjust them individually if needed.

2020-11-20 11:41 UTC, viccuad requested changes
Nice! and so fast :).

I have one concern, which is the new _pull-request-ci/isolate-network.sh_.

I wonder if it wouldn't be better to use Catapult's `make airgap-up` and `make airgap-down`, which is implemented for some k8s providers, and errors for those not implemented yet. Given that some providers need special settings (kind, minikube) or may not have support for networking plugins (CaaSP), so they need host/ssh access to change iptables, plugins, etc.
The Catapult targets are also used for airgap installs, hence why the policy includes the default ns too, as the docker registry is there when performing airgapped installs. We could simplify this.

If we don't call Catapult's `make airgap-{up,down}`, perhaps we should:
- Add another policy to airgap `$QUARKS_NAMESPACE`, and possibly `default` ns.
- Add a simple test to check that it is airgapped, since we could be missing the networking plugin for example.
- Add it as a kubecf make target, in _kubecf/scripts/_. It concerns me that we are duplicating efforts in GHA scripts and _kubecf/scripts_ as the first are not easily consumed downstream. While I expect _pull-request-ci/override-cats-properties.sh_ is to be moved in the future to _kubecf/scripts_ to comply with an rfd-9/10, _pull-request-ci/isolate-network.sh_ doesn't need to be, so why not have it directly in _kubecf/scripts/_.

2020-11-20 11:41 UTC, viccuad commented on .github/workflows/pull-request-ci.yaml
> +        continue-on-error: ${{ !matrix.ccdb-rotate }}
From what I can read, `continue-on-error` marks the step as green, even if it fails, which is dangerous.
I wonder if this line is needed if `fail-fast: false` is set.

Perhaps we want to set `fail-fast: true` and:
```
run: foo
if: experimental == true
```

But I may be misunderstanding things.
(same for the other instances of `continue-on-error` and the re-do of the experimental jobs in the PR).

2020-11-20 17:07 UTC, mook-as reviewed
Ah, I didn't realize `make airgap-{up,down}` existed, because I was looking at the catapult code which [didn't use it](https://github.com/SUSE/catapult/blob/a1f1ad3941a64fcd91824b6eff7471ced24998a0/modules/tests/kubecf-test.sh#L61).

Hmm, actually, looking at the implementation, `make airgap-up` is [only implemented for CaaSP](https://github.com/SUSE/catapult/blob/a1f1ad3941a64fcd91824b6eff7471ced24998a0/modules/experimental/airgap_up.sh#L7), so that wouldn't even work.

2020-11-20 17:36 UTC, viccuad commented
> Ah, I didn't realize `make airgap-{up,down}` existed, because I was looking at the catapult code which [didn't use it](https://github.com/SUSE/catapult/blob/a1f1ad3941a64fcd91824b6eff7471ced24998a0/modules/tests/kubecf-test.sh#L61).
> 
> Hmm, actually, looking at the implementation, `make airgap-up` is [only implemented for CaaSP](https://github.com/SUSE/catapult/blob/a1f1ad3941a64fcd91824b6eff7471ced24998a0/modules/experimental/airgap_up.sh#L7), so that wouldn't even work.

D'oh, true, the code for `make airgap-{up,down}` is on https://github.com/SUSE/catapult/pull/317.
(note that what you pointed to is `make module-experimental-airgap-up`, and old implementation which is backend dependent but is not in the backends module…).

I would argue that the point still stands, though.

2020-11-20 17:40 UTC, viccuad commented on .github/workflows/pull-request-ci.yaml
> +        continue-on-error: ${{ !matrix.ccdb-rotate }}
I see, thanks for the detailed explanation :).
It's just that `continue-on-error` always marks the step as green on UI, so we need to aware of that.

2020-11-20 17:50 UTC, viccuad submitted a review, later dismissed
Approving the PR as we talked on Slack. We can change the internetless part and consume catapult's `make airgap-up` if and once that lands :).

2020-11-24 15:16 UTC, viccuad approved these changes

2020-11-24 19:35 UTC, merged